FROM alpine:3.13.1
RUN apk add --no-cache \
    php7-fpm php7-curl php7-dom php7-exif php7-fileinfo php7-gd php7-iconv php7-imagick php7-json php7-mbstring \
    php7-mcrypt php7-mysqli php7-openssl php7-sodium php7-xml php7-xmlreader php7-zip php7-zlib  php7-ctype php7-session \
    supervisor \
    nginx


RUN rm -rf /etc/php7/php-fpm.d/www.conf
RUN rm -rf /etc/nginx/nginx.conf
RUN rm -rf /etc/php7/php.ini
RUN rm -rf /etc/supervisord.conf
RUN rm -rf /etc/nginx/conf.d/default.conf

RUN mkdir /dojoko-wp
COPY ./  /dojoko-wp/



RUN mkdir /var/log/php-fpm
RUN chown -R nobody.nobody /var/log/php-fpm


COPY /etc/ /tmp/

RUN mv /tmp/fpm-www.conf /etc/php7/php-fpm.d/www.conf
RUN mv /tmp/nginx.conf /etc/nginx/nginx.conf
RUN mv /tmp/php.ini /etc/php7/php.ini
RUN mv /tmp/supervisord_webonly.conf /etc/supervisord_webonly.conf



# RUN mysql -u dojoko -pdojoko@123$ dojoko < /dojoko-wp/seed/dojoko.sql
ENTRYPOINT ["supervisord", "--nodaemon", "--configuration", "/etc/supervisord_webonly.conf"]

#CMD ["sh"," /dojoko-wp/scripts/init.sh"]se


EXPOSE 80